require 'rubygems'
require 'rake'
require 'jeweler'
require 'rake/testtask'
require 'rcov/rcovtask'
require 'rake/rdoctask'

Jeweler::Tasks.new do |gem|
  gem.name = "KatamariDotei"
  gem.summary = %Q{"clod identification" - modular identification and quantification ms proteomics pipeline"}
  gem.description = %Q{"clod identification" - identifies & quantifies peptides in ms proteomics}
  gem.email = "jtprince@gmail.com"
  gem.homepage = "http://github.com/JesseJ/KatamariDotei"
  gem.authors = ["Jesse Jashinsky"]
  gem.add_development_dependency "spec-more", ">= 0"
  gem.has_rdoc = "yard"
end
Jeweler::GemcutterTasks.new

Rake::TestTask.new(:spec) do |spec|
  spec.libs << 'lib' << 'spec'
  spec.pattern = 'spec/**/*_spec.rb'
  spec.verbose = true
end

Rcov::RcovTask.new do |spec|
  spec.libs << 'spec'
  spec.pattern = 'spec/**/*_spec.rb'
  spec.verbose = true
end

task :default => :spec

Rake::RDocTask.new do |rdoc|
  version = File.exist?('VERSION') ? File.read('VERSION') : ""

  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "KatamariDotei #{version}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end
